steps:
  # Frontend Service
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/frontend:$COMMIT_SHA', './frontend']
    id: 'build-frontend'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/frontend:$COMMIT_SHA']
    id: 'push-frontend'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'frontend'
      - '--image=gcr.io/$PROJECT_ID/frontend:$COMMIT_SHA'
      - '--platform=managed'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - '--service-account=grancraft-deploy@$PROJECT_ID.iam.gserviceaccount.com'
    id: 'deploy-frontend'

  # File Service
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/file-service:$COMMIT_SHA', './services/file-service']
    id: 'build-file-service'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/file-service:$COMMIT_SHA']
    id: 'push-file-service'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'file-service'
      - '--image=gcr.io/$PROJECT_ID/file-service:$COMMIT_SHA'
      - '--platform=managed'
      - '--region=us-central1'
      - '--service-account=grancraft-deploy@$PROJECT_ID.iam.gserviceaccount.com'
    id: 'deploy-file-service'

  # Repeat similar steps for other services

images:
  - 'gcr.io/$PROJECT_ID/frontend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/file-service:$COMMIT_SHA'

timeout: 3600s 